spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/client_db
    username: sa
    password: ENC(AhaLswnxLl0teQu9BT+NhQ==) # password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 182164507246-8dhig02r1gvum3boqcjel0r77lspts0p.apps.googleusercontent.com
            client-secret: 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
            client_authentication_method: client_secret_post
            grant_type_method: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile

#        provider:  # well-known authz-server
#          google:
#            issuerUri: https://accounts.google.com


