spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/client_db
    # ~/client_db
      # url: jdbc:h2:mem:test  # in-memory ??
    username: sa
    #password: 1234
    password: ENC(AhaLswnxLl0teQu9BT+NhQ==)

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true